### PR TITLE
Modern IDs

### PR DESCRIPTION
**Pull request by davideaster**
Update applications for consistency with https://github.com/virtual-world-framework/vwf/pull/448.

@allisoncorey @scottnc27603 @eric79

### CODE REVIEW

**Comment by davideaster** [comment]
@scottnc27603, in `webrtc/style.css` is the id `#index-vwf` used? I don't see a node with that id created. We should probably generalize the rule to not be dependent on the application ID, or remove it if it isn't used.

**Comment by scottnc27603** [comment]
That's not something I remember changing, so whatever you think is best.

Scott

Sent from my iPhone
Scott Haynes
919 480 7800 cell

**Comment by allisoncorey** [comment]
:+1: 

The #index-vwf does not appear to be used. My guess is it was lingering from an old css file that was copied over. I'd remove.

**Comment by scottnc27603** [comment]
Actually, bzflag is searching for '#index.vwf' causes an error if it doesn' exist.  In bzflag/js/events.js the code gets the application ID and then searches for that id.  If that element is not found then the mousedown listener isn't setup.

**Comment by davideaster** [comment]
It's probably OK to remove the rule from the `webrtc` app's stylesheet. It seems to apply to the WebGL canvas, and I don't think `webrtc` ever has one.

The canvas is being given the VWF application ID as its DOM id. I presume that the threejs driver is doing this. bzflag searches using the application ID and isn't specifically looking for `index-vwf`. This is the relevant section:

    var sceneNode = vwf.find("","/")[0];
    var canvas = $('#' + sceneNode).get(0);

The new IDs have slashes in them:

    <canvas id="/duck/index.vwf" ...></canvas>

Maybe that makes an invalid DOM id?

**Comment by davideaster** [comment]
That DOM id should be OK for HTML5:

> The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. The value must not contain any space characters.

http://www.w3.org/TR/html5/dom.html#the-id-attribute

**Comment by scottnc27603** [comment]
bzflag issue:
document.getElementById returns the canvas correctly, the jquery call is failing.  Does anyone have a suggestion on how to fix this?

**Comment by davideaster** [comment]
Just for bzflag, we could look for the first canvas child of `#vwf-root`:

    $( "#vwf-root canvas" )

**Comment by scottnc27603** [comment]
Ok,  cool.  I've made that change and committed.

**Pull request merged**
